apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: input-binding
  namespace: default
spec:
  type: bindings.redis
  version: v1
  metadata:
  - name: redisHost
    value: "redis:6379"
  - name: redisPassword
    value: ""
  - name: operation
    value: get
